FROM python:3.8-slim-buster

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

RUN mkdir -p /home/connector

COPY requirements-connector.txt requirements.txt

RUN python -m pip install -r requirements.txt

WORKDIR /home/connector

COPY ./connector /home/connector

CMD python connector.py