FROM python:3.8-slim-buster

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

RUN mkdir -p /home/parser

COPY requirements-parser.txt requirements.txt

RUN python -m pip install -r requirements.txt

WORKDIR /home/parser

COPY ./parser /home/parser

CMD python parser-smarthub.py