FROM python:3.8-slim-buster

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

RUN mkdir -p /home/historian

COPY requirements-historian.txt requirements.txt

RUN python -m pip install -r requirements.txt

WORKDIR /home/historian

COPY ./historian /home/historian

CMD python historian.py